language: c
sudo: false
before_install:
  #- source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
  - source <(curl -SLs https://raw.githubusercontent.com/fede2cr/travis-ci-arduino/master/install.sh)
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
on_failure: change
